kind: Kustomization

namespace: argocd-stresstest

resources:
- appset.yaml
- argocd.yaml
- namespace.yaml
- secret.yaml

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: stresstest
  patch: |-
    - op: replace
      path: /spec/generators/0/git/repoURL
      value: "https://github.com/jgwest/knockout-argocd.git"
    - op: replace
      path: /spec/template/spec/source/repoURL
      value: "https://github.com/jgwest/knockout-argocd.git"
- target:
    version: v1
    kind: Secret
    name: my-repo
  patch: |-
    - op: replace
      path: /stringData/url
      value: "https://github.com/jgwest/knockout-argocd.git"
